### ISSUE TITLE
Update description for La Capitaine in README

### ISSUE THREAD

**Issue by keeferrourke** [erikdubois/themes-icons-pack#1]
Hey there, the index.theme for La Capitaine has been updated with an inherits line that has sane fallbacks for most systems. You should update your README to remove the instruction to modify the theme, since it is no longer necessary.

Cheers!

**Comment by keeferrourke** [comment]
I also just read your install scripts, and you can clone directly into `~/icons/la-capitaine` instead of cloning to `/tmp` and moving them around. This causes far fewer read/writes and will make install faster:

```
git clone https://github.com/keeferrourke/la-capitaine-icon-theme ~/.icons/la-capitaine
```

**Comment by keeferrourke** [comment]
any updates on this issue?

**Comment by erikdubois** [comment]
i definitely missed this one...
wait i do remember it...
have not been using this github in ages
not sure if I will keep it
just checked and people are using it...

**Comment by erikdubois** [comment]
keeping this github
changes have been made
